import sys

from .graph import AgentInputGraph
from .llms import ConversationLLM, RetrievalLLM, VerifyLLM, UpdateLLM, FillInputLLM, RouterLLM, FillCriteriaLLM, SelectMechLLM
from .model_manager import ModelManager
from .project_manager import ProjectManager
from .parameters import InputParameters, CriteriaParameters, FuelComponent
from CombustionAgent.agent_tool import AgentToolMechReduction

class Agent:

    def __init__(self, model_name: str, model_preprompts: list[str], model_opening_message: str, model_opening_message_criteria: str, database_path: str, project_path: str) -> None:

        self.project_manager = ProjectManager(project_path)
        self.model_manager = ModelManager(model_name)
        
        self.LLM_conversation = ConversationLLM(self.model_manager, model_preprompts[0], model_opening_message)
        self.LLM_retrieval = RetrievalLLM(self.model_manager, model_preprompts[1])
        self.LLM_verification = VerifyLLM(self.model_manager, model_preprompts[2])
        self.LLM_update = UpdateLLM(self.model_manager, model_preprompts[3])
        self.LLM_fill_input = FillInputLLM(self.model_manager, model_preprompts[4], database_path)
        self.LLM_router = RouterLLM(self.model_manager, model_preprompts[5])
        self.LLM_fill_criteria = FillCriteriaLLM(self.model_manager, model_preprompts[6])
        self.LLM_select_mechanism = SelectMechLLM(self.model_manager, model_preprompts[7])

        self.model_opening_message = model_opening_message
        self.model_opening_message_criteria = model_opening_message_criteria

        self.input_graph = AgentInputGraph(self, database_path)

    def main(self) -> None:

        selected_project_ID, new_project = self.project_manager.select_project()

        if(new_project):
            self.workflow()

        else:
            print()




    def workflow(self) -> None:

        input_parameters, process_history_input = self.run_input_graph()

        print("Complete history")
        print(process_history_input)

        criteria_parameters, process_history_criteria = self.run_criteria_graph()

        print(f"Criteria: {criteria_parameters}")
        print("History criteria retrieval process")
        print(process_history_criteria)

        # # self.model_manager.unload_model() #To do or not?

        # input_parameters = InputParameters(
        #     mechanism="Glarborg-2024-NH3",
        #     application_regime=None,
        #     fuel=[
        #         FuelComponent(species="H2", fraction=1.0)
        #     ],
        #     pressure_start=0.5,
        #     pressure_end=10.0,
        #     pressure_unit="bar",
        #     temperature_start=900.0,
        #     temperature_end=2000.0,
        #     temperature_unit="K",
        #     equivalence_ratio_start=0.5,
        #     equivalence_ratio_end=5.5,
        #     retained_species=["H2", "N2", "O2"],
        #     target_species=["H2"],
        # )

        list_mechanisms = self.run_mechanism_reduction(input_parameters)

        criteria_parameters = CriteriaParameters(IDT_accuracy = 1, species_reduction = 0.5, reactions_reduction = 0.5)

        # for testing the selection mechanism separately
        #list_mechanisms = ["2026-09-29-ID005-Glarborg-2024-NH3-error5", "2026-09-29-ID004-Glarborg-2024-NH3-error5", "2026-09-29-ID003-Glarborg-2024-NH3-error20"]

        reply_selection_mechanism = self.select_mechanism(criteria_parameters, list_mechanisms)
        # Add to history?, Use user input?

        print(f"\nAgent: {reply_selection_mechanism}")

        sys.exit()

    def run_input_graph(self) -> tuple[InputParameters, list[str]]:

        # complete process of input graph

        state = {
                "user_message": "",
                "process_history": [],
                "working_history": [],
                "input_parameters": InputParameters(),
                "route": None,
                "response": None,
            }

        print(f"\nAgent: {self.model_opening_message}")
        state["process_history"].append(f"Agent: {self.model_opening_message}")

        while True:
            try:
                user_input = input("\nYou: ")
                if user_input.lower() in ["exit", "quit"]:
                    self.model_manager.unload_model()
                    sys.exit()

                # Reset fields for new cycle
                state["working_history"] = []
                state["route"] = None

                # Update only the part of the state that changes
                state["user_message"] = user_input

                state["process_history"].append(f"User: {user_input}")

                # Run the LangGraph
                state = self.input_graph.app.invoke(state)

                if state["route"] == "END":
                    print("\nAgent found the good input parameters.\n")
                    break

                # Display the response generated by the chat node
                print(f"\nAgent: {state['response']}")

            except KeyboardInterrupt:
                self.model_manager.unload_model()
                sys.exit()

        return state["input_parameters"], state["process_history"]

    def run_criteria_graph(self) -> tuple[CriteriaParameters, list[str]]:

        process_history = []

        print(f"\nAgent: {self.model_opening_message_criteria}")
        process_history.append(f"Agent: {self.model_opening_message_criteria}")
 
        try:
            user_input = input("\nYou: ")
            if user_input.lower() in ["exit", "quit"]:
                self.model_manager.unload_model()
                sys.exit()

            process_history.append(f"User: {user_input}")

            LLM_fill_criteria_reply, criteria_parameters = self.LLM_fill_criteria.fill_criteria(user_input)

            process_history.append(f"FILL CRITERIA PARAMETERS: the agent has filled the criteria parameters and has assigned the weights as follows: {criteria_parameters}")

        except KeyboardInterrupt:
            self.model_manager.unload_model()
            sys.exit()

        return criteria_parameters, process_history


    def run_mechanism_reduction(self, input_parameters: InputParameters) -> list[str]:

        agent_tool_mechanism_reduction = AgentToolMechReduction()
        
        list_mechanisms = agent_tool_mechanism_reduction.run_drgep(input_parameters)
        print(list_mechanisms)

        return list_mechanisms

    def select_mechanism(self, criteria_paramters: CriteriaParameters, list_mechanisms: list[str]) -> str:

        # Provide mechanism + explanation

        reply_selected_mechanism = self.LLM_select_mechanism.select_mechanism(criteria_paramters, list_mechanisms)

        return reply_selected_mechanism