import sys

from .graph import AgentInputGraph
from .llms import ConversationLLM, RetrievalLLM, VerifyLLM, UpdateLLM, FillInputLLM, RouterLLM, FillCriteriaLLM
from .models import ModelManager
from .parameters import InputParameters, CriteriaParameters
from CombustionAgent.agent_tool import AgentToolMechReduction

class Agent:

    def __init__(self, model_name: str, model_preprompts: list[str], model_opening_message: str, model_opening_message_criteria: str, database_path: str) -> None:

        self.model_manager = ModelManager(model_name)
        
        self.LLM_conversation = ConversationLLM(self.model_manager, model_preprompts[0], model_opening_message)
        self.LLM_retrieval = RetrievalLLM(self.model_manager, model_preprompts[1])
        self.LLM_verification = VerifyLLM(self.model_manager, model_preprompts[2])
        self.LLM_update = UpdateLLM(self.model_manager, model_preprompts[3])
        self.LLM_fill_input = FillInputLLM(self.model_manager, model_preprompts[4], database_path)
        self.LLM_router = RouterLLM(self.model_manager, model_preprompts[5])
        self.LLM_fill_criteria = FillCriteriaLLM(self.model_manager, model_preprompts[6])

        self.model_opening_message = model_opening_message
        self.model_opening_message_criteria = model_opening_message_criteria

        self.input_graph = AgentInputGraph(self, database_path)

    def workflow(self) -> None:

        input_parameters, process_history = self.run_input_graph()

        print("Complete history")
        print(process_history)

        criteria_parameters, process_history = self.run_criteria_graph()

        #list_mechanisms = self.run_mechanism_reduction(input_parameters)

        #selected_mechanism = self.select_mechanism(list_mechanisms, criteria_parameters)

        #print(f"Selected mechanism by the agent: {selected_mechanism}")

        sys.exit()

    def run_input_graph(self) -> tuple[InputParameters, list[str]]:

        # complete process of input graph

        state = {
                "user_message": "",
                "process_history": [],
                "working_history": [],
                "input_parameters": InputParameters(),
                "route": None,
                "response": None,
            }

        print(f"\nAgent: {self.model_opening_message}")
        state["process_history"].append(f"Agent: {self.model_opening_message}")

        while True:
            try:
                user_input = input("\nYou: ")
                if user_input.lower() in ["exit", "quit"]: sys.exit()

                # Reset fields for new cycle
                state["working_history"] = []
                state["route"] = None

                # Update only the part of the state that changes
                state["user_message"] = user_input

                state["process_history"].append(f"User: {user_input}")

                # Run the LangGraph
                state = self.input_graph.app.invoke(state)

                if state["route"] == "END":
                    print("\nAgent found the good input parameters.\n")
                    self.model_manager.unload_model() #To do or not?
                    break

                # Display the response generated by the chat node
                print(f"\nAgent: {state['response']}")

            except KeyboardInterrupt:
                sys.exit()

        return state["input_parameters"], state["process_history"]

    def run_criteria_graph(self) -> tuple[CriteriaParameters, list[str]]:

        process_history = []

        print(f"\nAgent: {self.model_opening_message_criteria}")
        process_history.append(f"Agent: {self.model_opening_message_criteria}")
 
        try:
            user_input = input("\nYou: ")
            if user_input.lower() in ["exit", "quit"]: sys.exit()

            LLM_fill_criteria_reply, criteria_parameters = self.LLM_fill_criteria.fill_criteria(user_input)

        except KeyboardInterrupt:
            sys.exit()

        return criteria_parameters, process_history


    def run_mechanism_reduction(self, input_parameters: InputParameters) -> list[str]:

        agent_tool_mechanism_reduction = AgentToolMechReduction()
        
        list_mechanisms = agent_tool_mechanism_reduction.run_drgep(input_parameters)
        print(list_mechanisms)

        return list_mechanisms

    def select_mechanism(self, list_mechanisms: list[str], criteria_paramters: CriteriaParameters) -> str:

        selected_mechanism = ""

        return selected_mechanism